coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 4%
    patch:
      default:
        target: 50%

flags:
  gas2mqtt:
    paths:
      - apps/gas2mqtt/packages/src/
    carryforward: true
  jeelink2mqtt:
    paths:
      - apps/jeelink2mqtt/packages/src/
    carryforward: true
  vito2mqtt:
    paths:
      - apps/vito2mqtt/packages/src/
    carryforward: true
  velux2mqtt:
    paths:
      - apps/velux2mqtt/packages/src/
    carryforward: true
  airthings2mqtt:
    paths:
      - apps/airthings2mqtt/packages/src/
    carryforward: true
  caldates2mqtt:
    paths:
      - apps/caldates2mqtt/packages/src/
    carryforward: true
  suncast:
    paths:
      - apps/suncast/packages/src/
    carryforward: true
  wallpanel-control:
    paths:
      - apps/wallpanel-control/packages/src/
    carryforward: true

comment:
  layout: 'condensed_header, condensed_files, condensed_footer, components'
  behavior: default
  require_changes: true
