services:
  vito2mqtt:
    build:
      context: ../..
      dockerfile: apps/vito2mqtt/Dockerfile
    image: ghcr.io/ff-fab/vito2mqtt:latest
    restart: unless-stopped
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    group_add:
      - dialout
    env_file: .env
    environment:
      VITO2MQTT_MQTT__HOST: mosquitto
      VITO2MQTT_STORE_PATH: /app/data/store.json
    volumes:
      - vito2mqtt-data:/app/data
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - '1883:1883'
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

volumes:
  vito2mqtt-data:
  mosquitto-data:
  mosquitto-log:
