services:
  jeelink2mqtt:
    build:
      context: ../..
      dockerfile: apps/jeelink2mqtt/Dockerfile
    image: ghcr.io/ff-fab/jeelink2mqtt:latest
    restart: unless-stopped
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    env_file: .env
    environment:
      JEELINK2MQTT_SERIAL_PORT: /dev/ttyUSB0
      JEELINK2MQTT_MQTT__HOST: mosquitto
    volumes:
      - jeelink2mqtt-data:/app/data
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - '1883:1883'
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

volumes:
  jeelink2mqtt-data:
  mosquitto-data:
  mosquitto-log:
