services:
  wiz2mqtt:
    build:
      context: ../..
      dockerfile: apps/wiz2mqtt/Dockerfile
    restart: unless-stopped
    volumes:
      - wiz2mqtt-data:/app/data
    environment:
      WIZ2MQTT_MQTT__HOST: mosquitto
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - '127.0.0.1:1883:1883'
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

volumes:
  wiz2mqtt-data:
  mosquitto-data:
  mosquitto-log:
